# Generated by Django 4.2.2 on 2025-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=120, verbose_name='Nome da empresa')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('discord_url', models.URLField(blank=True, verbose_name='Discord')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato da Empresa',
                'verbose_name_plural': 'Contatos da Empresa',
            },
        ),
    ]
