# Generated by Django 4.2.2 on 2025-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_ultimas_postagens', models.BooleanField(default=False, verbose_name='Mostrar últimas 5 postagens')),
                ('mostrar_postagens_interagidas', models.BooleanField(default=False, verbose_name='Mostrar postagens com mais interações')),
                ('mostrar_secao_sobre', models.BooleanField(default=False, verbose_name='Mostrar seção "Sobre"')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Página Inicial',
                'verbose_name_plural': 'Configuração da Página Inicial',
            },
        ),
    ]
