# Generated by Django 4.2.2 on 2025-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comentariopostagemforum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagemforum',
            name='anexar_imagem',
        ),
        migrations.AlterField(
            model_name='postagemforum',
            name='descricao',
            field=models.TextField(max_length=5000, verbose_name='Descrição'),
        ),
    ]
