# Generated by Django 4.2.2 on 2025-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_postagemforum_anexar_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
