# Generated by Django 4.2.2 on 2025-11-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_postagemforum_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopostagemforum',
            name='conteudo',
            field=models.TextField(verbose_name='Comentário'),
        ),
    ]
